// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824162608_AddRolesAndPermissions")]
    partial class AddRolesAndPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Business_Logic.ActivityLogs.ActivityLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("log_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("character(10)")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_time");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("project_id");

                    b.Property<string>("TaskId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("task_id");

                    b.HasKey("LogId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Attachments.Attachment", b =>
                {
                    b.Property<string>("AttachmentId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attachment_location");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("project_id");

                    b.Property<string>("TaskId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("task_id");

                    b.HasKey("AttachmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Comments.Comment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("comment_id");

                    b.Property<DateTime?>("CommentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comment_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("character(10)")
                        .HasColumnName("employee_id");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("character(10)")
                        .HasColumnName("parent_comment_id");

                    b.Property<string>("TaskId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("task_id");

                    b.HasKey("CommentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TaskId");

                    b.ToTable("comments_", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Employees.Authentication", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("character(10)")
                        .HasColumnName("employee_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pass_word");

                    b.HasKey("EmployeeId");

                    b.ToTable("authentication", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Employees.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("character(10)")
                        .HasColumnName("employee_id");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int?>("EmployeeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("employee_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeLevel");

                    b.HasIndex("RoleId");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Employees.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permission_name");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Employees.PositionLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position");

                    b.HasKey("Level");

                    b.ToTable("position_level", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Employees.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Employees.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Priorities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority_name");

                    b.HasKey("PriorityId");

                    b.ToTable("priority", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Projects.Project", b =>
                {
                    b.Property<string>("ProjectID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("project_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("ProjectID");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Projects.ProjectMember", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("character(10)")
                        .HasColumnName("employee_id");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Statuses.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Tasks.TaskAssignee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("character(10)")
                        .HasColumnName("employee_id");

                    b.Property<string>("TaskId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("task_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_");

                    b.HasKey("EmployeeId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("task_assignees", (string)null);
                });

            modelBuilder.Entity("Business_Logic.Tasks.TaskItem", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("task_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_");

                    b.Property<string>("ParentTaskId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_task");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("TaskId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Business_Logic.ActivityLogs.ActivityLog", b =>
                {
                    b.HasOne("Business_Logic.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Business_Logic.Attachments.Attachment", b =>
                {
                    b.HasOne("Business_Logic.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Business_Logic.Comments.Comment", b =>
                {
                    b.HasOne("Business_Logic.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Comments.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Business_Logic.Employees.Authentication", b =>
                {
                    b.HasOne("Business_Logic.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Business_Logic.Employees.Employee", b =>
                {
                    b.HasOne("Business_Logic.Employees.PositionLevel", null)
                        .WithMany()
                        .HasForeignKey("EmployeeLevel")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Employees.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Business_Logic.Employees.RolePermission", b =>
                {
                    b.HasOne("Business_Logic.Employees.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Business_Logic.Employees.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Business_Logic.Projects.Project", b =>
                {
                    b.HasOne("Business_Logic.Priorities.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Statuses.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Business_Logic.Projects.ProjectMember", b =>
                {
                    b.HasOne("Business_Logic.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Business_Logic.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Business_Logic.Tasks.TaskAssignee", b =>
                {
                    b.HasOne("Business_Logic.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Business_Logic.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Business_Logic.Tasks.TaskItem", b =>
                {
                    b.HasOne("Business_Logic.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Priorities.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Business_Logic.Statuses.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
