name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore escape.sln

    - name: Build
      run: dotnet build escape.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Test
      run: dotnet test escape.sln --configuration ${{ matrix.configuration }} --no-build